import type { ModuleKey, Permission, UserRole } from '@/types'

export const rolePermissions: Record<UserRole, Permission[]> = {
  super_admin: [
    'platform.access',
    'core.access',
    'business.manage',
    'business.delete',
    'staff.manage',
    'staff.permissions.manage',
    'customers.manage',
    'customers.view_basic',
    'customers.create',
    'customers.edit',
    'crm.notes.add',
    'crm.tags.manage',
    'bookings.manage',
    'bookings.view',
    'bookings.view_assigned',
    'bookings.create',
    'bookings.edit',
    'bookings.cancel',
    'bookings.check_in',
    'bookings.update_status',
    'bookings.create_walk_in',
    'memberships.manage',
    'memberships.view',
    'memberships.assign',
    'pos.access',
    'pos.discount',
    'inventory.view',
    'inventory.adjust',
    'payments.process',
    'payments.refund',
    'payments.view',
    'reports.manage',
    'reports.view',
    'reports.export',
    'loyalty.manage',
    'records.delete',
    'notifications.manage',
    'marketing.manage',
    'branches.manage',
    'white_label.manage',
    'data.export',
    'data.backup.manage',
    'data.import',
    'ai.assistant.access',
    'settings.manage',
    'settings.view',
    'billing.manage',
    'packages.manage',
    'modules.manage',
    'subscriptions.manage',
    'module_access.override',
  ],
  owner: [
    'core.access',
    'business.manage',
    'staff.manage',
    'staff.permissions.manage',
    'customers.manage',
    'customers.create',
    'customers.edit',
    'crm.notes.add',
    'crm.tags.manage',
    'bookings.manage',
    'bookings.view',
    'bookings.create',
    'bookings.edit',
    'bookings.cancel',
    'bookings.check_in',
    'memberships.manage',
    'memberships.view',
    'memberships.assign',
    'pos.access',
    'pos.discount',
    'inventory.view',
    'inventory.adjust',
    'payments.process',
    'payments.refund',
    'payments.view',
    'reports.manage',
    'reports.view',
    'reports.export',
    'loyalty.manage',
    'records.delete',
    'notifications.manage',
    'marketing.manage',
    'branches.manage',
    'white_label.manage',
    'data.export',
    'data.backup.manage',
    'data.import',
    'ai.assistant.access',
    'settings.manage',
    'settings.view',
    'billing.manage',
  ],
  manager: [
    'core.access',
    'customers.manage',
    'customers.create',
    'customers.edit',
    'crm.notes.add',
    'crm.tags.manage',
    'bookings.manage',
    'bookings.view',
    'bookings.create',
    'bookings.edit',
    'bookings.cancel',
    'bookings.check_in',
    'memberships.manage',
    'memberships.view',
    'memberships.assign',
    'reports.manage',
    'reports.view',
    'pos.access',
    'pos.discount',
    'inventory.view',
    'inventory.adjust',
    'payments.process',
    'payments.view',
    'loyalty.manage',
    'notifications.manage',
    'marketing.manage',
    'branches.manage',
    'bookings.update_status',
    'bookings.create_walk_in',
    'customers.view_basic',
  ],
  staff: [
    'core.access',
    'bookings.view_assigned',
    'bookings.view',
    'bookings.update_status',
    'customers.view_basic',
    'bookings.create_walk_in',
  ],
  customer: [
    'customer.profile.view',
    'customer.booking.create',
    'customer.membership.view',
    'customer.rewards.view',
    'customer.history.view',
  ],
}

export const modulePermissionMap: Partial<Record<ModuleKey, Permission>> = {
  core: 'core.access',
  booking: 'bookings.view',
  membership: 'memberships.view',
  loyalty: 'loyalty.manage',
  pos: 'pos.access',
  inventory: 'inventory.view',
  staff_commission: 'staff.manage',
  payment: 'payments.view',
  notification: 'notifications.manage',
  reports: 'reports.view',
  marketing: 'marketing.manage',
  multi_branch: 'branches.manage',
  customer_portal: 'customer.profile.view',
  white_label: 'white_label.manage',
  data_ownership_backup: 'data.export',
  ai_assistant: 'ai.assistant.access',
}

export const moduleRequiredPackages: Partial<Record<ModuleKey, string>> = {
  core: 'Starter',
  booking: 'Starter',
  customer_portal: 'Starter',
  reports: 'Starter',
  membership: 'Growth',
  loyalty: 'Growth',
  payment: 'Growth',
  pos: 'Pro',
  inventory: 'Pro',
  staff_commission: 'Pro',
  notification: 'Pro',
  marketing: 'Business Suite',
  multi_branch: 'Business Suite',
  white_label: 'Enterprise',
  ai_assistant: 'Enterprise',
}

export function roleHasPermission(role: UserRole | undefined, permission: Permission) {
  if (!role) {
    return false
  }

  return rolePermissions[role].includes(permission)
}
